<?php

namespace Openmarco\Seriously\std;

/**@var array $attr */

use Openmarco\Seriously\Service\Data;
use Openmarco\Seriously\Control\Control;

?>

<label class="om-form-check">
	<input class="om-form-check-input" type="checkbox" data-om-cc-checkbox="true"<?php checked($attr[ATTR_VALUE]) ?>>
	<input<?php Control::attributes($attr) ?> type="hidden" value="<?php echo Data::pack($attr[ATTR_VALUE]) ?>">
	<?php if (array_key_exists('caption', $attr)) : ?>
		<?php echo esc_html($attr['caption']) ?>
	<?php endif ?>
</label>
