<?php

namespace Openmarco\Seriously\std;

/**@var array $attr */

use Openmarco\Seriously\Service\Data;
use Openmarco\Seriously\Control\Control;

?>

<div>
	<input type="number"
	       min="<?php echo esc_attr($attr['min']) ?>"
	       max="<?php echo esc_attr($attr['max']) ?>"
	       step="<?php echo esc_attr($attr['step']) ?>"
	       value="<?php echo esc_attr($attr[ATTR_VALUE]) ?>"
	       data-om-cc-number="true" />
	<input<?php Control::attributes($attr); ?> type="hidden" value="<?php echo Data::pack($attr[ATTR_VALUE]); ?>">
</div>